#!/bin/bash

export OATH_TMP_FILE=${HOME}/.oath.enc
export LOGINNAME="login.my.cluster"
export OATH_PUB_KEY=/usr/local/etc/public_key_2fa.pem
OATH_USER_FILE=/usr/local/etc/oath/$USER
OATH_HOTL="support@my.cluster"

add_user () {
    OATH_SEED=$( head -10 /dev/urandom | sha512sum | cut -b 1-30 )
    OATH_BASE32=$( oathtool -v $OATH_SEED | \
                   awk -F ': ' '$1 == "Base32 secret" { print $2 }')
    echo "$OATH_SEED" | \
        openssl rsautl -encrypt -inkey $OATH_PUB_KEY -pubin -out $OATH_TMP_FILE
    qrencode -t UTF8 \
        "otpauth://totp/${USER}@${LOGINNAME}?secret=${OATH_BASE32}"
}

if ! [[ -e $OATH_USER_FILE ]]; then
    add_user
    echo "This code is only shown once, please add it to your generator."
    echo "Please do not save copies of this code on systems you use to login."
    echo
    echo "If you close this window or session you won't be able to scan the"
    echo "qr-code anymore. You will need to contact support."
else
    echo "User $USER exists, please contact support:"
    echo "    $OATH_HOTL"
fi

echo
while true; do
    read  -p "Exit and close session (y/N) " close
    if echo " x${close}z "  | grep -qi " xyz "; then
        exit
    fi
done

exit
