#!/bin/bash

OATH_NODE=132.230.223.225
OATH_LOCAL_ETC=/usr/local/etc
OATH_REMOTE=/usr/local/etc/oath
OATH_USERS=/usr/local/etc/users.oath
OATH_KEY=/usr/local/etc/private_key_2fa.pem

if ! [[ -e ${OATH_LOCAL_ETC}/oath ]]; then
    /usr/bin/mkdir -p ${OATH_LOCAL_ETC}/oath
fi

/usr/bin/rsync -a --delete ${OATH_NODE}:${OATH_REMOTE}/ ${OATH_LOCAL_ETC}/oath/

echo "# Option  User    Prefix  Seed    LastOTP Timestamp" >${OATH_USERS}.new

for file in $( ls ${OATH_LOCAL_ETC}/oath/* ); do
    /usr/bin/openssl rsautl -decrypt -inkey $OATH_KEY -in $file \
        >>${OATH_USERS}.new
done

if ! diff -q ${OATH_USERS}.new ${OATH_USERS} >/dev/null; then
    mv ${OATH_USERS}.new ${OATH_USERS}
    /usr/bin/pdcp -g login,vis ${OATH_USERS} ${OATH_USERS}
else
    rm -f ${OATH_USERS}.new
fi
