#!/bin/bash
CONTENT_FILE=/tmp/content
SECRET=/etc/secret
ADDRESS='[2001:db8::1]'

cp -a $SECRET $CONTENT_FILE

while true; do 
  socat TCP6-LISTEN:165,bind=::1,reuseaddr OPEN:/dev/null || sleep 10
  for user in $(ls /home/*/.oath.enc | cut -d / -f 3); do
    echo Sending credentials for $user
    cat /home/$user/.oath.enc > $CONTENT_FILE
    echo $user >> $CONTENT_FILE
    cat $SECRET $CONTENT_FILE | openssl sha3-256 -binary | base64 >> $CONTENT_FILE
    socat OPEN:$CONTENT_FILE TCP-CONNECT:$ADDRESS:165
    mv /home/$user/.oath.enc /usr/local/etc/oath/$user
  done
done
